<?php
/**
 * Edit customer account
 *
 * @var $block \Moonlay\CustomerAttribute\Block\Account\Edit
 */
?>    
<?php $attributeHelper = $this->helper('Moonlay\CustomerAttribute\Helper\Customerattribute');?>
<?php $attributeCollection = $attributeHelper->getUserDefinedAttribures()?>
<?php if ($attributeCollection->getSize() > 0) : ?>
    <fieldset class="fieldset info">
        <!-- For all user defined attributes -->
        <?php foreach ($attributeCollection as $attribute) :?>
        <!-- For all user defined attributes which are set for customer edit account  -->
        <?php if ($attributeHelper->isAttribureForCustomerAccountEdit($attribute->getAttributeCode())) :?>
            <?php $frontEndLabel = $attribute->getStoreLabel($attributeHelper->getStoreId()); ?>
            <?php $getAttributeCodeFunction = "get" .  str_replace(' ', '', ucwords(str_replace('_', ' ', $attribute->getAttributeCode()))); ?>
            <?php $fieldRequiredClass = ($attribute->getIsRequired()) ? 'data-validate="{required:true}"' : '' ?>
            <?php $fieldFrontendClass = ($attribute->getFrontendClass()) ? $attribute->getFrontendClass() : '' ?>
            <?php $fieldValue = $attributeHelper->getCustomer($block->getCustomer()->getId())->getData($attribute->getAttributeCode());?>
            
            <?php if ($attribute->getFrontendInput()== 'text') :?>        
                <?php if ($attribute->getAttributeCode()== 'firstname_kana') :?>  
                    <div class="div-name-kana-frist <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()) :?>required<?php endif;?>">
                        <input type="text" placeholder="たんじろう" name="<?php echo $attribute->getAttributeCode(); ?>" id="<?php echo $attribute->getAttributeCode(); ?>" value="<?php echo $block->escapeHtml($fieldValue) ?>" title="<?php echo __($frontEndLabel) ?>" class="input-text input-text-name-jpn <?php echo $fieldFrontendClass ;?>" <?php echo $fieldRequiredClass; ?>>                               
                    </div>
                <?php elseif ($attribute->getAttributeCode()== 'lastname_kana') :?>
                    <div class="div-name-kana-last <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()) :?>required<?php endif;?>">
                        <input type="text" placeholder="かまど" name="<?php echo $attribute->getAttributeCode(); ?>" id="<?php echo $attribute->getAttributeCode(); ?>" value="<?php echo $block->escapeHtml($fieldValue) ?>" title="<?php echo __($frontEndLabel) ?>" class="input-text input-text-name-jpn <?php echo $fieldFrontendClass ;?>" <?php echo $fieldRequiredClass; ?>>
                    </div> 
                <?php endif; ?>        
            <?php endif; ?>

        <?php endif; ?>
        <?php endforeach;?>
    </fieldset>
<?php endif; ?>