<?php 
/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */

$product = $block->getProduct();
$content = $product->getData('size_information');

$om = \Magento\Framework\App\ObjectManager::getInstance();
$filterManager = $om->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter();

$size_tab = $filterManager->filter($content);

echo $size_tab;
?>