<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Book $block */
?>
<h2 class="title-edit-account">Address Book</h2>

<div class="block block-addresses-default div-book">

    <div class="block-title title2-addres-info"><?= $block->escapeHtml(__('Default Addresses')) ?></div>

    <div class="block-content">

        <?php if ($_pAddsses = $block->getDefaultBilling()) : ?>
            <div class="box box-address-billing">
                <a class="box-title title3-addres-info">
                    <span class="title-defauld"><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
                </a>
                <div class="box-content">
                    <address class = "title4-addres-info">
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a class="action edit changes-defauld-link" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <span  class="change-defauld"><?= $block->escapeHtml(__('Change Billing Address')) ?></span>
                    </a>
                </div>
            </div>

        <?php else : ?>
            <div class="box box-billing-address">
                <a class="box-title title3-addres-info"><span><?= $block->escapeHtml(__('Default Billing Address')) ?></span></a>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default billing address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>

        <?php if ($_pAddsses = $block->getDefaultShipping()) : ?>
            <div class="box box-address-shipping">
                <a class="box-title title3-addres-info">
                    <span class="title-defauld"><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
                </a>
                <div class="box-content">
                    <address class = "title4-addres-info">
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a class="action edit changes-defauld-link" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <span class="change-defauld"><?= $block->escapeHtml(__('Change Shipping Address')) ?></span>
                    </a>
                </div>
            </div>

        <?php else : ?>
            <div class="box box-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span></strong>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default shipping address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
