<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Edit $block */
?>

<form class="form form-edit-account delete-margin-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info add-border-full-name-ect-account">

        <?= $block->getBlockHtml('formkey') ?>

        <a class="fullname-edit-account">Fullname</a>
        <?= $block->getLayout()->createBlock(\Moonlay\CustomEditAccount\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>

        <!-- <a class="fullname-edit-account">Name (Kana)</a> -->
        <?= $block->getChildHtml('form_additional_info') ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>


        <?php if ($_dob->isEnabled()) : ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()) : ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <div class="field choice chekbox-edit-account">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
            <label class="label checkbox-edt-account-label" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()) : ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label checkbox-edt-account-label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>
    </fieldset>

    <fieldset class="fieldset password margin-changes-pssamdemail back-edit-passsandemail width-changes-email-and-pass" data-container="change-email-password">
        <h2 class="title-chages-passandemail"><span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span></h2>

        <div class="field email required delete-margin-buttom-edt-cgnages" data-container="change-email">
            <div class="control">
                <input type="email" placeholder="New Email" name="email" id="email" data-input="change-email" value="" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text input-text-login" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>

        <div class="field password current required delete-margin-buttom-edt-cgnages">
            <div class="control">
                <input type="password" placeholder="Current Password" class="input-text input-text-login" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>

        <div class="field new password required delete-margin-buttom-edt-cgnages" data-container="new-password">
            <div class="control">
                <input type="password" placeholder="New Password" class="input-text input-text-login" name="password" id="password"
                    data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="field confirm password required delete-margin-buttom-edt-cgnages" data-container="confirm-password">
            <div class="control">
                <input type="password" placeholder="Confrim New Password" class="input-text input-text-login" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>

    </fieldset>
    
    <div class="actions-toolbar dic-btn-edit-account">
        <div class="primary dic-btn-edit-account">
            <button type="submit" class="action save primary btn-edit-account" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
    </div>

</form>

<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()) : ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else : ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
