<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password main-forgot-pss"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>

    <div class="title-frgt-pass">
        <h2 style="text-align: center;" class="jpn">パスワードをお忘れですか</h2>
        <h2 style="text-align: center;" class="eng">Forgot Password</h2>
    </div>

    <fieldset class="fieldset">
        <div class="field email required">
            <div class="control">
                <input type="email" placeholder="Enter your email" name="email" alt="email" id="email_address" class="input-text input-text-login" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    
    <div class="actions-toolbar">
        <div class="primary btn-frgt">
            <button type="submit" class="action submit primary btn-login" style="float: none !important;"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
