<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login center">

    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">

                

                <div class="field email required">
                    <div class="control">
                        <input name="login[username]" placeholder="Email" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text input-text-login" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>

                <div class="field password required">
                    <div class="control">
                        <input name="login[password]" type="password" placeholder="Password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text input-text-login" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                
                <?= $block->getChildHtml('form_additional_info') ?>
                
                <div>                    
                    <div class = "margin-frgt-andbtn-login">
                        <a class="action remind Forgot-Password" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Password?')) ?></span></a>
                    </div>
                    <div style = "text-align: center">
                        <button type="submit" class="action login primary btn-login" name="send" id="send2"><span><?= $block->escapeHtml(__('Log In')) ?></span></button>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
</div>

