<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Customer additional info for register and login forms
 *
 */
?>
<div class="margin-buttom-name-register">
    <div class="field field-name-firstname required">                
        <input type="text" placeholder="First Name"
            style="float: left"
            class="input-text input-text-name">
            
    </div>

    <div class="field field-name-lastname required">
        <input type="text" placeholder="Last Name"            
            style="float: right"
            class="input-text input-text-name">             
    </div>
</div>
